name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Hello World
        id: hello_world_step
        run: |
          echo "Hello, World!"
          echo "::set-output name=message::Hello, World!"

  approve_job:
    runs-on: ubuntu-latest
    outputs:
      steps: context
    steps:
      - name: Manual Approval
        id: approve_step
        run: echo "approved"
          
  welcome_message_job:
    needs: hello_world_job
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'push' && needs.approve_job.outputs.approve_step == matrix.approval

    strategy:
      matrix:
        approval: ["approved"]

    steps:
      - name: Print Welcome Message
        run: echo "${{ needs.hello_world_job.outputs.message }}"
